#!/usr/bin/python
import sys,xenv,os.path

if __name__ == '__main__':
    xenv.set_modul_path()
    argv = sys.argv
    
    main_cmd = os.path.basename(argv[0])
    cmd_line = main_cmd
    for word in argv[1:] :
       cmd_line = cmd_line + " " + word    
    import xcmd , define
    import impl.console , impl.cmd_parser, impl.conf_iter ,impl.conf_yaml
    testRoot = os.path.dirname(os.path.realpath(__file__))
    testRoot = os.path.dirname(testRoot)
    data     = impl.conf_yaml.load_conf(testRoot + "/test/data/conf.yml","!","define.")
    cmder    = xcmd.commander(main_cmd)
    impl.cmd_parser.parse(cmd_line,cmder) 
    iter     = impl.conf_iter.node_iter(data)
    impl.console.complement(cmder,iter)
    print(cmder)
