#!/usr/bin/python
import sys

if __name__ == '__main__':
    import env
    env.set_module_path()
    cmdline = sys.argv[1:]
    import impl.console 
    testRoot = os.path.dirname(os.path.realpath(__file__))
    testRoot = os.path.dirname(testRoot)
    data     = load_conf(testRoot + "/data/conf.yml","!","define.")
    cmder    = define.commander()
    iter     = define.node_iter(data,cmder)

    impl.console.run(cmdline)
    code = 0
    exit(code)
